// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using cobblersBackend.Data;

#nullable disable

namespace cobblersBackend.Migrations
{
    [DbContext(typeof(CobblersDbContext))]
    [Migration("20260717151954_RenameTaskSetTablesToAssignmentSet")]
    partial class RenameTaskSetTablesToAssignmentSet
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("cobblersBackend.Data.Entities.Assignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("content_json");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("GradingJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("grading_json");

                    b.Property<string>("Hint")
                        .HasColumnType("text")
                        .HasColumnName("hint");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<string>("SampleSolutionJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("sample_solution_json");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_assignment");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_assignment_slug");

                    b.ToTable("assignment", null, t =>
                        {
                            t.HasCheckConstraint("ck_assignment_kind", "kind IN ('code', 'predict', 'project')");
                        });
                });

            modelBuilder.Entity("cobblersBackend.Data.Entities.AssignmentSet", b =>
                {
                    b.Property<string>("AssignmentSetId")
                        .HasColumnType("text")
                        .HasColumnName("assignment_set_id");

                    b.Property<string>("DisplayTitle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_title");

                    b.HasKey("AssignmentSetId")
                        .HasName("pk_assignment_set");

                    b.ToTable("assignment_set", (string)null);
                });

            modelBuilder.Entity("cobblersBackend.Data.Entities.AssignmentSetAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AssignmentId")
                        .HasColumnType("integer")
                        .HasColumnName("assignment_id");

                    b.Property<string>("AssignmentSetId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("assignment_set_id");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer")
                        .HasColumnName("order_index");

                    b.HasKey("Id")
                        .HasName("pk_assignment_set_assignment");

                    b.HasIndex("AssignmentId")
                        .HasDatabaseName("ix_assignment_set_assignment_assignment_id");

                    b.HasIndex("AssignmentSetId", "AssignmentId")
                        .IsUnique()
                        .HasDatabaseName("ix_assignment_set_assignment_assignment_set_id_assignment_id");

                    b.HasIndex("AssignmentSetId", "OrderIndex")
                        .IsUnique()
                        .HasDatabaseName("ix_assignment_set_assignment_assignment_set_id_order_index");

                    b.ToTable("assignment_set_assignment", (string)null);
                });

            modelBuilder.Entity("cobblersBackend.Data.Entities.Attendance", b =>
                {
                    b.Property<string>("StudentId")
                        .HasColumnType("text")
                        .HasColumnName("student_id");

                    b.Property<string>("SessionId")
                        .HasColumnType("text")
                        .HasColumnName("session_id");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("StudentId", "SessionId")
                        .HasName("pk_attendance");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_attendance_session_id");

                    b.ToTable("attendance", (string)null);
                });

            modelBuilder.Entity("cobblersBackend.Data.Entities.Session", b =>
                {
                    b.Property<string>("SessionId")
                        .HasColumnType("text")
                        .HasColumnName("session_id");

                    b.Property<string>("AssignmentSetId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("assignment_set_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("SessionId")
                        .HasName("pk_session");

                    b.HasIndex("AssignmentSetId")
                        .HasDatabaseName("ix_session_assignment_set_id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_session_code");

                    b.ToTable("session", (string)null);
                });

            modelBuilder.Entity("cobblersBackend.Data.Entities.Student", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.HasKey("Id")
                        .HasName("pk_student");

                    b.ToTable("student", (string)null);
                });

            modelBuilder.Entity("cobblersBackend.Data.Entities.Submission", b =>
                {
                    b.Property<Guid>("SubId")
                        .HasColumnType("uuid")
                        .HasColumnName("sub_id");

                    b.Property<int>("AssignmentId")
                        .HasColumnType("integer")
                        .HasColumnName("assignment_id");

                    b.Property<string>("ContentJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("content_json");

                    b.Property<bool?>("Passed")
                        .HasColumnType("boolean")
                        .HasColumnName("passed");

                    b.Property<string>("ResultJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("result_json");

                    b.Property<string>("SessionId")
                        .HasColumnType("text")
                        .HasColumnName("session_id");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("student_id");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("SubId")
                        .HasName("pk_submission");

                    b.HasIndex("AssignmentId")
                        .HasDatabaseName("ix_submission_assignment_id");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_submission_session_id");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("ix_submission_student_id");

                    b.ToTable("submission", (string)null);
                });

            modelBuilder.Entity("cobblersBackend.Data.Entities.AssignmentSetAssignment", b =>
                {
                    b.HasOne("cobblersBackend.Data.Entities.Assignment", "Assignment")
                        .WithMany("AssignmentSets")
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_assignment_set_assignment_assignment_assignment_id");

                    b.HasOne("cobblersBackend.Data.Entities.AssignmentSet", "AssignmentSet")
                        .WithMany("Assignments")
                        .HasForeignKey("AssignmentSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_assignment_set_assignment_assignment_set_assignment_set_id");

                    b.Navigation("Assignment");

                    b.Navigation("AssignmentSet");
                });

            modelBuilder.Entity("cobblersBackend.Data.Entities.Attendance", b =>
                {
                    b.HasOne("cobblersBackend.Data.Entities.Session", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_attendance_session_session_id");

                    b.HasOne("cobblersBackend.Data.Entities.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_attendance_student_student_id");

                    b.Navigation("Session");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("cobblersBackend.Data.Entities.Session", b =>
                {
                    b.HasOne("cobblersBackend.Data.Entities.AssignmentSet", "AssignmentSet")
                        .WithMany("Sessions")
                        .HasForeignKey("AssignmentSetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_session_assignment_set_assignment_set_id");

                    b.Navigation("AssignmentSet");
                });

            modelBuilder.Entity("cobblersBackend.Data.Entities.Submission", b =>
                {
                    b.HasOne("cobblersBackend.Data.Entities.Assignment", "Assignment")
                        .WithMany("Submissions")
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_submission_assignment_assignment_id");

                    b.HasOne("cobblersBackend.Data.Entities.Session", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_submission_session_session_id");

                    b.HasOne("cobblersBackend.Data.Entities.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_submission_student_student_id");

                    b.Navigation("Assignment");

                    b.Navigation("Session");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("cobblersBackend.Data.Entities.Assignment", b =>
                {
                    b.Navigation("AssignmentSets");

                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("cobblersBackend.Data.Entities.AssignmentSet", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
