// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using cobblersBackend.Data;

#nullable disable

namespace cobblersBackend.Migrations
{
    [DbContext(typeof(CobblersDbContext))]
    partial class CobblersDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("cobblersBackend.Data.Entities.Attendance", b =>
                {
                    b.Property<string>("StudentId")
                        .HasColumnType("text")
                        .HasColumnName("student_id");

                    b.Property<string>("SessionId")
                        .HasColumnType("text")
                        .HasColumnName("session_id");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.HasKey("StudentId", "SessionId")
                        .HasName("pk_attendance");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_attendance_session_id");

                    b.ToTable("attendance", (string)null);
                });

            modelBuilder.Entity("cobblersBackend.Data.Entities.Session", b =>
                {
                    b.Property<string>("SessionId")
                        .HasColumnType("text")
                        .HasColumnName("session_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreateDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_date_time");

                    b.Property<string>("TaskSetId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("task_set_id");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("SessionId")
                        .HasName("pk_session");

                    b.HasIndex("TaskSetId")
                        .HasDatabaseName("ix_session_task_set_id");

                    b.HasIndex("Code", "Year")
                        .IsUnique()
                        .HasDatabaseName("ix_session_code_year");

                    b.ToTable("session", (string)null);
                });

            modelBuilder.Entity("cobblersBackend.Data.Entities.Student", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.HasKey("Id")
                        .HasName("pk_student");

                    b.ToTable("student", (string)null);
                });

            modelBuilder.Entity("cobblersBackend.Data.Entities.Submission", b =>
                {
                    b.Property<Guid>("SubId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("sub_id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ContentJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("content_json");

                    b.Property<bool?>("Passed")
                        .HasColumnType("boolean")
                        .HasColumnName("passed");

                    b.Property<string>("ResultJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("result_json");

                    b.Property<string>("SessionId")
                        .HasColumnType("text")
                        .HasColumnName("session_id");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("student_id");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<int>("TaskId")
                        .HasColumnType("integer")
                        .HasColumnName("task_id");

                    b.HasKey("SubId")
                        .HasName("pk_submission");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_submission_session_id");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("ix_submission_student_id");

                    b.HasIndex("TaskId")
                        .HasDatabaseName("ix_submission_task_id");

                    b.ToTable("submission", (string)null);
                });

            modelBuilder.Entity("cobblersBackend.Data.Entities.Task", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("content_json");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Hint")
                        .HasColumnType("text")
                        .HasColumnName("hint");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<string>("SampleSolutionJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("sample_solution_json");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_task");

                    b.ToTable("task", null, t =>
                        {
                            t.HasCheckConstraint("ck_task_kind", "kind IN ('code', 'predict', 'project')");
                        });
                });

            modelBuilder.Entity("cobblersBackend.Data.Entities.TaskSet", b =>
                {
                    b.Property<string>("TaskSetId")
                        .HasColumnType("text")
                        .HasColumnName("task_set_id");

                    b.Property<string>("DisplayTitle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_title");

                    b.HasKey("TaskSetId")
                        .HasName("pk_task_set");

                    b.ToTable("task_set", (string)null);
                });

            modelBuilder.Entity("cobblersBackend.Data.Entities.TaskSetTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("TaskId")
                        .HasColumnType("integer")
                        .HasColumnName("task_id");

                    b.Property<string>("TaskSetId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("task_set_id");

                    b.HasKey("Id")
                        .HasName("pk_task_set_task");

                    b.HasIndex("TaskId")
                        .HasDatabaseName("ix_task_set_task_task_id");

                    b.HasIndex("TaskSetId", "TaskId")
                        .IsUnique()
                        .HasDatabaseName("ix_task_set_task_task_set_id_task_id");

                    b.ToTable("task_set_task", (string)null);
                });

            modelBuilder.Entity("cobblersBackend.Data.Entities.Attendance", b =>
                {
                    b.HasOne("cobblersBackend.Data.Entities.Session", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_attendance_session_session_id");

                    b.HasOne("cobblersBackend.Data.Entities.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_attendance_student_student_id");

                    b.Navigation("Session");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("cobblersBackend.Data.Entities.Session", b =>
                {
                    b.HasOne("cobblersBackend.Data.Entities.TaskSet", "TaskSet")
                        .WithMany("Sessions")
                        .HasForeignKey("TaskSetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_session_task_set_task_set_id");

                    b.Navigation("TaskSet");
                });

            modelBuilder.Entity("cobblersBackend.Data.Entities.Submission", b =>
                {
                    b.HasOne("cobblersBackend.Data.Entities.Session", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_submission_session_session_id");

                    b.HasOne("cobblersBackend.Data.Entities.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_submission_student_student_id");

                    b.HasOne("cobblersBackend.Data.Entities.Task", "Task")
                        .WithMany("Submissions")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_submission_task_task_id");

                    b.Navigation("Session");

                    b.Navigation("Student");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("cobblersBackend.Data.Entities.TaskSetTask", b =>
                {
                    b.HasOne("cobblersBackend.Data.Entities.Task", "Task")
                        .WithMany("TaskSets")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_task_set_task_task_task_id");

                    b.HasOne("cobblersBackend.Data.Entities.TaskSet", "TaskSet")
                        .WithMany("Tasks")
                        .HasForeignKey("TaskSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_task_set_task_task_set_task_set_id");

                    b.Navigation("Task");

                    b.Navigation("TaskSet");
                });

            modelBuilder.Entity("cobblersBackend.Data.Entities.Task", b =>
                {
                    b.Navigation("Submissions");

                    b.Navigation("TaskSets");
                });

            modelBuilder.Entity("cobblersBackend.Data.Entities.TaskSet", b =>
                {
                    b.Navigation("Sessions");

                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
